"use server";

import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { isCategory } from "@/lib/categories";

export type Result = { error?: string };

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
// Allow a little clock skew between phone and server.
const FUTURE_SLACK_MS = 2 * 60 * 1000;

function isId(v: unknown): v is string {
  return typeof v === "string" && UUID.test(v);
}

function isInt(v: unknown, min: number, max: number): v is number {
  return typeof v === "number" && Number.isInteger(v) && v >= min && v <= max;
}

function toIso(ms: unknown) {
  if (typeof ms !== "number" || !Number.isFinite(ms)) return null;
  if (ms > Date.now() + FUTURE_SLACK_MS) return null;
  return new Date(ms).toISOString();
}

function cleanNotes(v: unknown) {
  if (typeof v !== "string") return null;
  const t = v.trim().slice(0, 2000);
  return t === "" ? null : t;
}

function done(error?: { message: string } | null): Result {
  if (error) return { error: error.message };
  revalidatePath("/", "layout");
  return {};
}

const FUTURE = { error: "That time is in the future." };

// ---- actions -------------------------------------------------------------
// Each mutation is a single database round trip; ids are generated by the client
// so the optimistic UI and the saved row share the same id.

const COLOR = /^#[0-9a-fA-F]{6}$/;

function cleanName(v: unknown) {
  return typeof v === "string" && v.trim() !== "" ? v.trim().slice(0, 60) : null;
}

/**
 * Creates an action. `endAt: null` starts a live one that runs until you end it;
 * a number stores a finished action with both stamps.
 */
export async function addAction(input: {
  id: string;
  typeId: string;
  name: string;
  category: string;
  color: string;
  at: number;
  endAt: number | null;
  effort?: number | null;
  notes?: string | null;
}): Promise<Result> {
  const name = cleanName(input.name);
  if (!isId(input.id) || !isId(input.typeId) || !name || !isCategory(input.category)) {
    return { error: "Unknown action type." };
  }
  const startedAt = toIso(input.at);
  if (!startedAt) return FUTURE;
  let endedAt: string | null = null;
  if (input.endAt !== null) {
    endedAt = toIso(input.endAt);
    if (!endedAt) return FUTURE;
    if (input.endAt < input.at) return { error: "End time is before the start." };
  }
  const effort = input.effort ?? null;
  if (effort !== null && !isInt(effort, 1, 10)) return { error: "Effort is 1–10." };

  const supabase = await createClient();
  const res = await supabase.from("actions").insert({
    id: input.id,
    type_id: input.typeId,
    name,
    category: input.category,
    color: COLOR.test(input.color) ? input.color : "#2f5d50",
    started_at: startedAt,
    ended_at: endedAt,
    effort,
    notes: cleanNotes(input.notes),
  });
  return done(res.error);
}

export async function endAction(input: { id: string; at: number }): Promise<Result> {
  if (!isId(input.id)) return { error: "Unknown action." };
  const endedAt = toIso(input.at);
  if (!endedAt) return FUTURE;

  const supabase = await createClient();
  const { data, error } = await supabase
    .from("actions")
    .update({ ended_at: endedAt })
    .eq("id", input.id)
    .lte("started_at", endedAt)
    .select("id");
  if (error) return { error: error.message };
  if (!data?.length) return { error: "End time is before the start." };
  return done();
}

export async function updateAction(input: {
  id: string;
  startedAt: number;
  endedAt: number | null;
  effort: number | null;
  notes: string | null;
}): Promise<Result> {
  if (!isId(input.id)) return { error: "Unknown action." };
  const startedAt = toIso(input.startedAt);
  if (!startedAt) return FUTURE;
  let endedAt: string | null = null;
  if (input.endedAt !== null) {
    endedAt = toIso(input.endedAt);
    if (!endedAt) return FUTURE;
    if (input.endedAt < input.startedAt) return { error: "End time is before the start." };
  }
  if (input.effort !== null && !isInt(input.effort, 1, 10)) return { error: "Effort is 1–10." };

  const supabase = await createClient();
  const res = await supabase
    .from("actions")
    .update({
      started_at: startedAt,
      ended_at: endedAt,
      effort: input.effort,
      notes: cleanNotes(input.notes),
    })
    .eq("id", input.id);
  return done(res.error);
}

export async function deleteAction(id: string): Promise<Result> {
  if (!isId(id)) return { error: "Unknown action." };
  const supabase = await createClient();
  return done((await supabase.from("actions").delete().eq("id", id)).error);
}

// ---- pain ----------------------------------------------------------------

export async function addPainLevel(input: { id: string; level: number; at: number }): Promise<Result> {
  if (!isId(input.id)) return { error: "Bad id." };
  if (!isInt(input.level, 0, 10)) return { error: "Pain level is 0–10." };
  const recordedAt = toIso(input.at);
  if (!recordedAt) return FUTURE;
  const supabase = await createClient();
  const res = await supabase
    .from("pain_levels")
    .insert({ id: input.id, level: input.level, recorded_at: recordedAt });
  return done(res.error);
}

export async function deletePainLevel(id: string): Promise<Result> {
  if (!isId(id)) return { error: "Unknown reading." };
  const supabase = await createClient();
  return done((await supabase.from("pain_levels").delete().eq("id", id)).error);
}

export async function addPainEvent(input: {
  id: string;
  typeId: string;
  name: string;
  color: string;
  at: number;
  intensity: number | null;
}): Promise<Result> {
  const name = cleanName(input.name);
  if (!isId(input.id) || !isId(input.typeId) || !name) return { error: "Unknown pain type." };
  if (input.intensity !== null && !isInt(input.intensity, 0, 10)) return { error: "Intensity is 0–10." };
  const occurredAt = toIso(input.at);
  if (!occurredAt) return FUTURE;

  const supabase = await createClient();
  const res = await supabase.from("pain_events").insert({
    id: input.id,
    type_id: input.typeId,
    name,
    color: COLOR.test(input.color) ? input.color : "#c23a3a",
    occurred_at: occurredAt,
    intensity: input.intensity,
  });
  return done(res.error);
}

export async function updatePainEvent(input: {
  id: string;
  at: number;
  intensity: number | null;
  notes: string | null;
}): Promise<Result> {
  if (!isId(input.id)) return { error: "Unknown pain event." };
  if (input.intensity !== null && !isInt(input.intensity, 0, 10)) return { error: "Intensity is 0–10." };
  const occurredAt = toIso(input.at);
  if (!occurredAt) return FUTURE;
  const supabase = await createClient();
  const res = await supabase
    .from("pain_events")
    .update({ occurred_at: occurredAt, intensity: input.intensity, notes: cleanNotes(input.notes) })
    .eq("id", input.id);
  return done(res.error);
}

export async function deletePainEvent(id: string): Promise<Result> {
  if (!isId(id)) return { error: "Unknown pain event." };
  const supabase = await createClient();
  return done((await supabase.from("pain_events").delete().eq("id", id)).error);
}

// ---- whole day -----------------------------------------------------------

const DAY_MIN_MS = 22 * 3_600_000;
const DAY_MAX_MS = 26 * 3_600_000;

/** Deletes everything in one local day: actions overlapping it, readings and events. */
export async function clearDay(input: { startMs: number; endMs: number }): Promise<Result> {
  const { startMs, endMs } = input;
  const length = endMs - startMs;
  if (!Number.isFinite(startMs) || length < DAY_MIN_MS || length > DAY_MAX_MS) {
    return { error: "Bad day range." };
  }
  if (startMs > Date.now() + FUTURE_SLACK_MS) return FUTURE;

  const start = new Date(startMs).toISOString();
  const end = new Date(endMs).toISOString();
  const supabase = await createClient();

  const results = await Promise.all([
    supabase.from("actions").delete().lt("started_at", end).or(`ended_at.is.null,ended_at.gt.${start}`),
    supabase.from("pain_levels").delete().gte("recorded_at", start).lt("recorded_at", end),
    supabase.from("pain_events").delete().gte("occurred_at", start).lt("occurred_at", end),
  ]);
  const failed = results.find((r) => r.error)?.error;
  return done(failed);
}
